// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAzjOOi3oF82vsB1vvX79JoJrl6d-yrj4',
    appId: '1:914380146036:web:ebb42fd7760de4eb55d821',
    messagingSenderId: '914380146036',
    projectId: 'freepay-394fb',
    authDomain: 'freepay-394fb.firebaseapp.com',
    storageBucket: 'freepay-394fb.appspot.com',
    measurementId: 'G-Z21XZGM00N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjpAtq_kiacR-WnqNPS59TDoXZcKlh3Rw',
    appId: '1:914380146036:android:41fca05f718ab73055d821',
    messagingSenderId: '914380146036',
    projectId: 'freepay-394fb',
    storageBucket: 'freepay-394fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy4H_ISpHRa7mkbxLdJuipuwcb83WiQTY',
    appId: '1:914380146036:ios:9ca5ffb5d4c0b4d155d821',
    messagingSenderId: '914380146036',
    projectId: 'freepay-394fb',
    storageBucket: 'freepay-394fb.appspot.com',
    iosClientId:
        '914380146036-d6teqq1df9gl7qgam93870dpropr54k5.apps.googleusercontent.com',
    iosBundleId: 'com.deepeshkalura.freepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy4H_ISpHRa7mkbxLdJuipuwcb83WiQTY',
    appId: '1:914380146036:ios:9ca5ffb5d4c0b4d155d821',
    messagingSenderId: '914380146036',
    projectId: 'freepay-394fb',
    storageBucket: 'freepay-394fb.appspot.com',
    iosClientId:
        '914380146036-d6teqq1df9gl7qgam93870dpropr54k5.apps.googleusercontent.com',
    iosBundleId: 'com.deepeshkalura.freepay',
  );
}
